#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokédex order
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum NationalDexOrder
{
    NATIONAL_DEX_NONE,
    NATIONAL_DEX_BULBASAUR,
    NATIONAL_DEX_IVYSAUR,
    NATIONAL_DEX_VENUSAUR,
    NATIONAL_DEX_CHARMANDER,
    NATIONAL_DEX_CHARMELEON,
    NATIONAL_DEX_CHARIZARD,
    NATIONAL_DEX_SQUIRTLE,
    NATIONAL_DEX_WARTORTLE,
    NATIONAL_DEX_BLASTOISE,
    NATIONAL_DEX_PIDGEY,
    NATIONAL_DEX_PIDGEOTTO,
    NATIONAL_DEX_PIDGEOT,
    NATIONAL_DEX_WEEDLE,
    NATIONAL_DEX_KAKUNA,
    NATIONAL_DEX_BEEDRILL,
    NATIONAL_DEX_RATTATA,
    NATIONAL_DEX_RATICATE,
    NATIONAL_DEX_SPEAROW,
    NATIONAL_DEX_FEAROW,
    NATIONAL_DEX_EKANS,
    NATIONAL_DEX_ARBOK,
    NATIONAL_DEX_SANDSHREW,
    NATIONAL_DEX_SANDSLASH,
    NATIONAL_DEX_NIDORAN_F,
    NATIONAL_DEX_NIDORINA,
    NATIONAL_DEX_NIDOQUEEN,
    NATIONAL_DEX_NIDORAN_M,
    NATIONAL_DEX_NIDORINO,
    NATIONAL_DEX_NIDOKING,
    NATIONAL_DEX_ZUBAT,
    NATIONAL_DEX_GOLBAT,
    NATIONAL_DEX_CROBAT,
    NATIONAL_DEX_PARAS,
    NATIONAL_DEX_PARASECT,
    NATIONAL_DEX_DIGLETT,
    NATIONAL_DEX_DUGTRIO,
    NATIONAL_DEX_MEOWTH,
    NATIONAL_DEX_PERSIAN,
    NATIONAL_DEX_PERRSERKER,
    NATIONAL_DEX_MANKEY,
    NATIONAL_DEX_PRIMEAPE,
    NATIONAL_DEX_ANNIHILAPE,
    NATIONAL_DEX_GROWLITHE,
    NATIONAL_DEX_ARCANINE,
    NATIONAL_DEX_POLIWAG,
    NATIONAL_DEX_POLIWHIRL,
    NATIONAL_DEX_POLIWRATH,
    NATIONAL_DEX_POLITOED,
    NATIONAL_DEX_MACHOP,
    NATIONAL_DEX_MACHOKE,
    NATIONAL_DEX_MACHAMP,
    NATIONAL_DEX_BELLSPROUT,
    NATIONAL_DEX_WEEPINBELL,
    NATIONAL_DEX_VICTREEBEL,
    NATIONAL_DEX_GEODUDE,
    NATIONAL_DEX_GRAVELER,
    NATIONAL_DEX_GOLEM,
    NATIONAL_DEX_PONYTA,
    NATIONAL_DEX_RAPIDASH,
    NATIONAL_DEX_SLOWPOKE,
    NATIONAL_DEX_SLOWBRO,
    NATIONAL_DEX_SLOWKING,
    NATIONAL_DEX_FARFETCHD,
    NATIONAL_DEX_SIRFETCHD,
    NATIONAL_DEX_DODUO,
    NATIONAL_DEX_DODRIO,
    NATIONAL_DEX_GASTLY,
    NATIONAL_DEX_HAUNTER,
    NATIONAL_DEX_GENGAR,
    NATIONAL_DEX_ONIX,
    NATIONAL_DEX_STEELIX,
    NATIONAL_DEX_CUBONE,
    NATIONAL_DEX_MAROWAK,
    NATIONAL_DEX_TYROGUE,
    NATIONAL_DEX_HITMONLEE,
    NATIONAL_DEX_HITMONCHAN,
    NATIONAL_DEX_HITMONTOP,
    NATIONAL_DEX_RHYHORN,
    NATIONAL_DEX_RHYDON,
    NATIONAL_DEX_RHYPERIOR,
    NATIONAL_DEX_CHANSEY,
    NATIONAL_DEX_KANGASKHAN,
    NATIONAL_DEX_HORSEA,
    NATIONAL_DEX_SEADRA,
    NATIONAL_DEX_KINGDRA,
    NATIONAL_DEX_SCYTHER,
    NATIONAL_DEX_SCIZOR,
    NATIONAL_DEX_KLEAVOR,
    NATIONAL_DEX_MAGBY,
    NATIONAL_DEX_MAGMAR,
    NATIONAL_DEX_MAGMORTAR,
    NATIONAL_DEX_TAUROS,
    NATIONAL_DEX_MAGIKARP,
    NATIONAL_DEX_GYARADOS,
    NATIONAL_DEX_OMANYTE,
    NATIONAL_DEX_OMASTAR,
    NATIONAL_DEX_KABUTO,
    NATIONAL_DEX_KABUTOPS,
    NATIONAL_DEX_AERODACTYL,
    NATIONAL_DEX_MUNCHLAX,
    NATIONAL_DEX_SNORLAX,
    NATIONAL_DEX_DRATINI,
    NATIONAL_DEX_DRAGONAIR,
    NATIONAL_DEX_DRAGONITE,
    NATIONAL_DEX_MEW,
    NATIONAL_DEX_CHIKORITA,
    NATIONAL_DEX_BAYLEEF,
    NATIONAL_DEX_MEGANIUM,
    NATIONAL_DEX_CYNDAQUIL,
    NATIONAL_DEX_QUILAVA,
    NATIONAL_DEX_TYPHLOSION,
    NATIONAL_DEX_TOTODILE,
    NATIONAL_DEX_CROCONAW,
    NATIONAL_DEX_FERALIGATR,
    NATIONAL_DEX_SENTRET,
    NATIONAL_DEX_FURRET,
    NATIONAL_DEX_HOOTHOOT,
    NATIONAL_DEX_NOCTOWL,
    NATIONAL_DEX_SPINARAK,
    NATIONAL_DEX_ARIADOS,
    NATIONAL_DEX_TOGEPI,
    NATIONAL_DEX_TOGETIC,
    NATIONAL_DEX_TOGEKISS,
    NATIONAL_DEX_NATU,
    NATIONAL_DEX_XATU,
    NATIONAL_DEX_MAREEP,
    NATIONAL_DEX_FLAAFFY,
    NATIONAL_DEX_AMPHAROS,
    NATIONAL_DEX_BONSLY,
    NATIONAL_DEX_SUDOWOODO,
    NATIONAL_DEX_HOPPIP,
    NATIONAL_DEX_SKIPLOOM,
    NATIONAL_DEX_JUMPLUFF,
    NATIONAL_DEX_AIPOM,
    NATIONAL_DEX_AMBIPOM,
    NATIONAL_DEX_SUNKERN,
    NATIONAL_DEX_SUNFLORA,
    NATIONAL_DEX_YANMA,
    NATIONAL_DEX_YANMEGA,
    NATIONAL_DEX_WOOPER,
    NATIONAL_DEX_QUAGSIRE,
    NATIONAL_DEX_CLODSIRE,
    NATIONAL_DEX_UNOWN,
    NATIONAL_DEX_MURKROW,
    NATIONAL_DEX_HONCHKROW,
    NATIONAL_DEX_GIRAFARIG,
    NATIONAL_DEX_FARIGIRAF,
    NATIONAL_DEX_PINECO,
    NATIONAL_DEX_FORRETRESS,
    NATIONAL_DEX_DUNSPARCE,
    NATIONAL_DEX_DUDUNSPARCE,
    NATIONAL_DEX_GLIGAR,
    NATIONAL_DEX_GLISCOR,
    NATIONAL_DEX_QWILFISH,
    NATIONAL_DEX_OVERQWIL,
    NATIONAL_DEX_SHUCKLE,
    NATIONAL_DEX_HERACROSS,
    NATIONAL_DEX_SNEASEL,
    NATIONAL_DEX_SNEASLER,
    NATIONAL_DEX_SLUGMA,
    NATIONAL_DEX_MAGCARGO,
    NATIONAL_DEX_CORSOLA,
    NATIONAL_DEX_CURSOLA,
    NATIONAL_DEX_REMORAID,
    NATIONAL_DEX_OCTILLERY,
    NATIONAL_DEX_HOUNDOUR,
    NATIONAL_DEX_HOUNDOOM,
    NATIONAL_DEX_PHANPY,
    NATIONAL_DEX_DONPHAN,
    NATIONAL_DEX_STANTLER,
    NATIONAL_DEX_WYRDEER,
    NATIONAL_DEX_RAIKOU,
    NATIONAL_DEX_ENTEI,
    NATIONAL_DEX_SUICUNE,
    NATIONAL_DEX_LARVITAR,
    NATIONAL_DEX_PUPITAR,
    NATIONAL_DEX_TYRANITAR,
    NATIONAL_DEX_CELEBI,
    NATIONAL_DEX_TREECKO,
    NATIONAL_DEX_GROVYLE,
    NATIONAL_DEX_SCEPTILE,
    NATIONAL_DEX_TORCHIC,
    NATIONAL_DEX_COMBUSKEN,
    NATIONAL_DEX_BLAZIKEN,
    NATIONAL_DEX_MUDKIP,
    NATIONAL_DEX_MARSHTOMP,
    NATIONAL_DEX_SWAMPERT,
    NATIONAL_DEX_POOCHYENA,
    NATIONAL_DEX_MIGHTYENA,
    NATIONAL_DEX_ZIGZAGOON,
    NATIONAL_DEX_LINOONE,
    NATIONAL_DEX_OBSTAGOON,
    NATIONAL_DEX_LOTAD,
    NATIONAL_DEX_LOMBRE,
    NATIONAL_DEX_LUDICOLO,
    NATIONAL_DEX_SEEDOT,
    NATIONAL_DEX_NUZLEAF,
    NATIONAL_DEX_SHIFTRY,
    NATIONAL_DEX_TAILLOW,
    NATIONAL_DEX_SWELLOW,
    NATIONAL_DEX_RALTS,
    NATIONAL_DEX_KIRLIA,
    NATIONAL_DEX_GARDEVOIR,
    NATIONAL_DEX_GALLADE,
    NATIONAL_DEX_SURSKIT,
    NATIONAL_DEX_MASQUERAIN,
    NATIONAL_DEX_SHROOMISH,
    NATIONAL_DEX_BRELOOM,
    NATIONAL_DEX_SLAKOTH,
    NATIONAL_DEX_VIGOROTH,
    NATIONAL_DEX_SLAKING,
    NATIONAL_DEX_NINCADA,
    NATIONAL_DEX_NINJASK,
    NATIONAL_DEX_SHEDINJA,
    NATIONAL_DEX_WHISMUR,
    NATIONAL_DEX_LOUDRED,
    NATIONAL_DEX_EXPLOUD,
    NATIONAL_DEX_MAKUHITA,
    NATIONAL_DEX_HARIYAMA,
    NATIONAL_DEX_AZURILL,
    NATIONAL_DEX_MARILL,
    NATIONAL_DEX_AZUMARILL,
    NATIONAL_DEX_NOSEPASS,
    NATIONAL_DEX_PROBOPASS,
    NATIONAL_DEX_SABLEYE,
    NATIONAL_DEX_MAWILE,
    NATIONAL_DEX_ARON,
    NATIONAL_DEX_LAIRON,
    NATIONAL_DEX_AGGRON,
    NATIONAL_DEX_ELECTRIKE,
    NATIONAL_DEX_MANECTRIC,
    NATIONAL_DEX_VOLBEAT,
    NATIONAL_DEX_ILLUMISE,
    NATIONAL_DEX_BUDEW,
    NATIONAL_DEX_ROSELIA,
    NATIONAL_DEX_ROSERADE,
    NATIONAL_DEX_GULPIN,
    NATIONAL_DEX_SWALOT,
    NATIONAL_DEX_CARVANHA,
    NATIONAL_DEX_SHARPEDO,
    NATIONAL_DEX_WAILMER,
    NATIONAL_DEX_WAILORD,
    NATIONAL_DEX_NUMEL,
    NATIONAL_DEX_CAMERUPT,
    NATIONAL_DEX_TRAPINCH,
    NATIONAL_DEX_VIBRAVA,
    NATIONAL_DEX_FLYGON,
    NATIONAL_DEX_CACNEA,
    NATIONAL_DEX_CACTURNE,
    NATIONAL_DEX_SWABLU,
    NATIONAL_DEX_ALTARIA,
    NATIONAL_DEX_ZANGOOSE,
    NATIONAL_DEX_SEVIPER,
    NATIONAL_DEX_LUNATONE,
    NATIONAL_DEX_SOLROCK,
    NATIONAL_DEX_BARBOACH,
    NATIONAL_DEX_WHISCASH,
    NATIONAL_DEX_BALTOY,
    NATIONAL_DEX_CLAYDOL,
    NATIONAL_DEX_LILEEP,
    NATIONAL_DEX_CRADILY,
    NATIONAL_DEX_ANORITH,
    NATIONAL_DEX_ARMALDO,
    NATIONAL_DEX_FEEBAS,
    NATIONAL_DEX_MILOTIC,
    NATIONAL_DEX_KECLEON,
    NATIONAL_DEX_DUSKULL,
    NATIONAL_DEX_DUSCLOPS,
    NATIONAL_DEX_DUSKNOIR,
    NATIONAL_DEX_ABSOL,
    NATIONAL_DEX_SNORUNT,
    NATIONAL_DEX_GLALIE,
    NATIONAL_DEX_FROSLASS,
    NATIONAL_DEX_CLAMPERL,
    NATIONAL_DEX_GOREBYSS,
    NATIONAL_DEX_HUNTAIL,
    NATIONAL_DEX_RELICANTH,
    NATIONAL_DEX_BAGON,
    NATIONAL_DEX_SHELGON,
    NATIONAL_DEX_SALAMENCE,
    NATIONAL_DEX_BELDUM,
    NATIONAL_DEX_METANG,
    NATIONAL_DEX_METAGROSS,
    NATIONAL_DEX_REGIROCK,
    NATIONAL_DEX_REGICE,
    NATIONAL_DEX_REGISTEEL,
    NATIONAL_DEX_KYOGRE,
    NATIONAL_DEX_GROUDON,
    NATIONAL_DEX_RAYQUAZA,
    NATIONAL_DEX_DEOXYS,
    NATIONAL_DEX_TURTWIG,
    NATIONAL_DEX_GROTLE,
    NATIONAL_DEX_TORTERRA,
    NATIONAL_DEX_CHIMCHAR,
    NATIONAL_DEX_MONFERNO,
    NATIONAL_DEX_INFERNAPE,
    NATIONAL_DEX_PIPLUP,
    NATIONAL_DEX_PRINPLUP,
    NATIONAL_DEX_EMPOLEON,
    NATIONAL_DEX_STARLY,
    NATIONAL_DEX_STARAVIA,
    NATIONAL_DEX_STARAPTOR,
    NATIONAL_DEX_BIDOOF,
    NATIONAL_DEX_BIBAREL,
    NATIONAL_DEX_SHINX,
    NATIONAL_DEX_LUXIO,
    NATIONAL_DEX_LUXRAY,
    NATIONAL_DEX_CRANIDOS,
    NATIONAL_DEX_RAMPARDOS,
    NATIONAL_DEX_SHIELDON,
    NATIONAL_DEX_BASTIODON,
    NATIONAL_DEX_BURMY,
    NATIONAL_DEX_WORMADAM,
    NATIONAL_DEX_MOTHIM,
    NATIONAL_DEX_COMBEE,
    NATIONAL_DEX_VESPIQUEN,
    NATIONAL_DEX_BUIZEL,
    NATIONAL_DEX_FLOATZEL,
    NATIONAL_DEX_SHELLOS,
    NATIONAL_DEX_GASTRODON,
    NATIONAL_DEX_DRIFLOON,
    NATIONAL_DEX_DRIFBLIM,
    NATIONAL_DEX_BUNEARY,
    NATIONAL_DEX_LOPUNNY,
    NATIONAL_DEX_STUNKY,
    NATIONAL_DEX_SKUNTANK,
    NATIONAL_DEX_BRONZOR,
    NATIONAL_DEX_BRONZONG,
    NATIONAL_DEX_SPIRITOMB,
    NATIONAL_DEX_GIBLE,
    NATIONAL_DEX_GABITE,
    NATIONAL_DEX_GARCHOMP,
    NATIONAL_DEX_RIOLU,
    NATIONAL_DEX_LUCARIO,
    NATIONAL_DEX_HIPPOPOTAS,
    NATIONAL_DEX_HIPPOWDON,
    NATIONAL_DEX_SKORUPI,
    NATIONAL_DEX_DRAPION,
    NATIONAL_DEX_CROAGUNK,
    NATIONAL_DEX_TOXICROAK,
    NATIONAL_DEX_CARNIVINE,
    NATIONAL_DEX_FINNEON,
    NATIONAL_DEX_LUMINEON,
    NATIONAL_DEX_SNOVER,
    NATIONAL_DEX_ABOMASNOW,
    NATIONAL_DEX_UXIE,
    NATIONAL_DEX_MESPRIT,
    NATIONAL_DEX_AZELF,
    NATIONAL_DEX_DIALGA,
    NATIONAL_DEX_PALKIA,
    NATIONAL_DEX_REGIGIGAS,
    NATIONAL_DEX_GIRATINA,
    NATIONAL_DEX_CRESSELIA,
    NATIONAL_DEX_DARKRAI,
    NATIONAL_DEX_ARCEUS,
    NATIONAL_DEX_VICTINI,
    NATIONAL_DEX_PATRAT,
    NATIONAL_DEX_WATCHOG,
    NATIONAL_DEX_PURRLOIN,
    NATIONAL_DEX_LIEPARD,
    NATIONAL_DEX_PANSAGE,
    NATIONAL_DEX_SIMISAGE,
    NATIONAL_DEX_PANSEAR,
    NATIONAL_DEX_SIMISEAR,
    NATIONAL_DEX_PANPOUR,
    NATIONAL_DEX_SIMIPOUR,
    NATIONAL_DEX_BLITZLE,
    NATIONAL_DEX_ZEBSTRIKA,
    NATIONAL_DEX_ROGGENROLA,
    NATIONAL_DEX_BOLDORE,
    NATIONAL_DEX_GIGALITH,
    NATIONAL_DEX_DRILBUR,
    NATIONAL_DEX_EXCADRILL,
    NATIONAL_DEX_AUDINO,
    NATIONAL_DEX_TIMBURR,
    NATIONAL_DEX_GURDURR,
    NATIONAL_DEX_CONKELDURR,
    NATIONAL_DEX_TYMPOLE,
    NATIONAL_DEX_PALPITOAD,
    NATIONAL_DEX_SEISMITOAD,
    NATIONAL_DEX_THROH,
    NATIONAL_DEX_SAWK,
    NATIONAL_DEX_SEWADDLE,
    NATIONAL_DEX_SWADLOON,
    NATIONAL_DEX_LEAVANNY,
    NATIONAL_DEX_VENIPEDE,
    NATIONAL_DEX_WHIRLIPEDE,
    NATIONAL_DEX_SCOLIPEDE,
    NATIONAL_DEX_PETILIL,
    NATIONAL_DEX_LILLIGANT,
    NATIONAL_DEX_BASCULIN,
    NATIONAL_DEX_BASCULEGION,
    NATIONAL_DEX_SANDILE,
    NATIONAL_DEX_KROKOROK,
    NATIONAL_DEX_KROOKODILE,
    NATIONAL_DEX_DARUMAKA,
    NATIONAL_DEX_DARMANITAN,
    NATIONAL_DEX_MARACTUS,
    NATIONAL_DEX_DWEBBLE,
    NATIONAL_DEX_CRUSTLE,
    NATIONAL_DEX_SCRAGGY,
    NATIONAL_DEX_SCRAFTY,
    NATIONAL_DEX_SIGILYPH,
    NATIONAL_DEX_YAMASK,
    NATIONAL_DEX_RUNERIGUS,
    NATIONAL_DEX_TIRTOUGA,
    NATIONAL_DEX_CARRACOSTA,
    NATIONAL_DEX_ARCHEN,
    NATIONAL_DEX_ARCHEOPS,
    NATIONAL_DEX_ZORUA,
    NATIONAL_DEX_ZOROARK,
    NATIONAL_DEX_SOLOSIS,
    NATIONAL_DEX_DUOSION,
    NATIONAL_DEX_REUNICLUS,
    NATIONAL_DEX_KARRABLAST,
    NATIONAL_DEX_ESCAVALIER,
    NATIONAL_DEX_FOONGUS,
    NATIONAL_DEX_AMOONGUSS,
    NATIONAL_DEX_FRILLISH,
    NATIONAL_DEX_JELLICENT,
    NATIONAL_DEX_JOLTIK,
    NATIONAL_DEX_GALVANTULA,
    NATIONAL_DEX_FERROSEED,
    NATIONAL_DEX_FERROTHORN,
    NATIONAL_DEX_TYNAMO,
    NATIONAL_DEX_EELEKTRIK,
    NATIONAL_DEX_EELEKTROSS,
    NATIONAL_DEX_ELGYEM,
    NATIONAL_DEX_BEHEEYEM,
    NATIONAL_DEX_LITWICK,
    NATIONAL_DEX_LAMPENT,
    NATIONAL_DEX_CHANDELURE,
    NATIONAL_DEX_AXEW,
    NATIONAL_DEX_FRAXURE,
    NATIONAL_DEX_HAXORUS,
    NATIONAL_DEX_CRYOGONAL,
    NATIONAL_DEX_SHELMET,
    NATIONAL_DEX_ACCELGOR,
    NATIONAL_DEX_STUNFISK,
    NATIONAL_DEX_MIENFOO,
    NATIONAL_DEX_MIENSHAO,
    NATIONAL_DEX_DRUDDIGON,
    NATIONAL_DEX_GOLETT,
    NATIONAL_DEX_GOLURK,
    NATIONAL_DEX_PAWNIARD,
    NATIONAL_DEX_BISHARP,
    NATIONAL_DEX_KINGAMBIT,
    NATIONAL_DEX_RUFFLET,
    NATIONAL_DEX_BRAVIARY,
    NATIONAL_DEX_VULLABY,
    NATIONAL_DEX_MANDIBUZZ,
    NATIONAL_DEX_HEATMOR,
    NATIONAL_DEX_DURANT,
    NATIONAL_DEX_DEINO,
    NATIONAL_DEX_ZWEILOUS,
    NATIONAL_DEX_HYDREIGON,
    NATIONAL_DEX_LARVESTA,
    NATIONAL_DEX_VOLCARONA,
    NATIONAL_DEX_TORNADUS,
    NATIONAL_DEX_THUNDURUS,
    NATIONAL_DEX_RESHIRAM,
    NATIONAL_DEX_ZEKROM,
    NATIONAL_DEX_LANDORUS,
    NATIONAL_DEX_KYUREM,
    NATIONAL_DEX_GENESECT,
    NATIONAL_DEX_CHESPIN,
    NATIONAL_DEX_QUILLADIN,
    NATIONAL_DEX_CHESNAUGHT,
    NATIONAL_DEX_FENNEKIN,
    NATIONAL_DEX_BRAIXEN,
    NATIONAL_DEX_DELPHOX,
    NATIONAL_DEX_FROAKIE,
    NATIONAL_DEX_FROGADIER,
    NATIONAL_DEX_GRENINJA,
    NATIONAL_DEX_FLETCHLING,
    NATIONAL_DEX_FLETCHINDER,
    NATIONAL_DEX_TALONFLAME,
    NATIONAL_DEX_LITLEO,
    NATIONAL_DEX_PYROAR,
    NATIONAL_DEX_PANCHAM,
    NATIONAL_DEX_PANGORO,
    NATIONAL_DEX_ESPURR,
    NATIONAL_DEX_MEOWSTIC,
    NATIONAL_DEX_HONEDGE,
    NATIONAL_DEX_DOUBLADE,
    NATIONAL_DEX_AEGISLASH,
    NATIONAL_DEX_INKAY,
    NATIONAL_DEX_MALAMAR,
    NATIONAL_DEX_BINACLE,
    NATIONAL_DEX_BARBARACLE,
    NATIONAL_DEX_SKRELP,
    NATIONAL_DEX_DRAGALGE,
    NATIONAL_DEX_CLAUNCHER,
    NATIONAL_DEX_CLAWITZER,
    NATIONAL_DEX_TYRUNT,
    NATIONAL_DEX_TYRANTRUM,
    NATIONAL_DEX_AMAURA,
    NATIONAL_DEX_AURORUS,
    NATIONAL_DEX_CARBINK,
    NATIONAL_DEX_GOOMY,
    NATIONAL_DEX_SLIGGOO,
    NATIONAL_DEX_GOODRA,
    NATIONAL_DEX_PHANTUMP,
    NATIONAL_DEX_TREVENANT,
    NATIONAL_DEX_PUMPKABOO,
    NATIONAL_DEX_GOURGEIST,
    NATIONAL_DEX_NOIBAT,
    NATIONAL_DEX_NOIVERN,
    NATIONAL_DEX_ZYGARDE,
    NATIONAL_DEX_DIANCIE,
    NATIONAL_DEX_VOLCANION,
    NATIONAL_DEX_ROWLET,
    NATIONAL_DEX_DARTRIX,
    NATIONAL_DEX_DECIDUEYE,
    NATIONAL_DEX_LITTEN,
    NATIONAL_DEX_TORRACAT,
    NATIONAL_DEX_INCINEROAR,
    NATIONAL_DEX_POPPLIO,
    NATIONAL_DEX_BRIONNE,
    NATIONAL_DEX_PRIMARINA,
    NATIONAL_DEX_CRABRAWLER,
    NATIONAL_DEX_CRABOMINABLE,
    NATIONAL_DEX_ROCKRUFF,
    NATIONAL_DEX_LYCANROC,
    NATIONAL_DEX_WISHIWASHI,
    NATIONAL_DEX_MAREANIE,
    NATIONAL_DEX_TOXAPEX,
    NATIONAL_DEX_MUDBRAY,
    NATIONAL_DEX_MUDSDALE,
    NATIONAL_DEX_DEWPIDER,
    NATIONAL_DEX_ARAQUANID,
    NATIONAL_DEX_FOMANTIS,
    NATIONAL_DEX_LURANTIS,
    NATIONAL_DEX_MORELULL,
    NATIONAL_DEX_SHIINOTIC,
    NATIONAL_DEX_SALANDIT,
    NATIONAL_DEX_SALAZZLE,
    NATIONAL_DEX_STUFFUL,
    NATIONAL_DEX_BEWEAR,
    NATIONAL_DEX_BOUNSWEET,
    NATIONAL_DEX_STEENEE,
    NATIONAL_DEX_TSAREENA,
    NATIONAL_DEX_WIMPOD,
    NATIONAL_DEX_GOLISOPOD,
    NATIONAL_DEX_TYPE_NULL,
    NATIONAL_DEX_SILVALLY,
    NATIONAL_DEX_KOMALA,
    NATIONAL_DEX_TURTONATOR,
    NATIONAL_DEX_TOGEDEMARU,
    NATIONAL_DEX_BRUXISH,
    NATIONAL_DEX_DRAMPA,
    NATIONAL_DEX_JANGMO_O,
    NATIONAL_DEX_HAKAMO_O,
    NATIONAL_DEX_KOMMO_O,
    NATIONAL_DEX_COSMOG,
    NATIONAL_DEX_COSMOEM,
    NATIONAL_DEX_LUNALA,
    NATIONAL_DEX_SOLGALEO,
    NATIONAL_DEX_NIHILEGO,
    NATIONAL_DEX_BUZZWOLE,
    NATIONAL_DEX_PHEROMOSA,
    NATIONAL_DEX_XURKITREE,
    NATIONAL_DEX_CELESTEELA,
    NATIONAL_DEX_KARTANA,
    NATIONAL_DEX_GUZZLORD,
    NATIONAL_DEX_NECROZMA,
    NATIONAL_DEX_POIPOLE,
    NATIONAL_DEX_NAGANADEL,
    NATIONAL_DEX_STAKATAKA,
    NATIONAL_DEX_BLACEPHALON,
    NATIONAL_DEX_ZERAORA,
    NATIONAL_DEX_ROOKIDEE,
    NATIONAL_DEX_CORVISQUIRE,
    NATIONAL_DEX_CORVIKNIGHT,
    NATIONAL_DEX_BLIPBUG,
    NATIONAL_DEX_DOTTLER,
    NATIONAL_DEX_ORBEETLE,
    NATIONAL_DEX_GOSSIFLEUR,
    NATIONAL_DEX_ELDEGOSS,
    NATIONAL_DEX_CHEWTLE,
    NATIONAL_DEX_DREDNAW,
    NATIONAL_DEX_ROLYCOLY,
    NATIONAL_DEX_CARKOL,
    NATIONAL_DEX_COALOSSAL,
    NATIONAL_DEX_APPLIN,
    NATIONAL_DEX_FLAPPLE,
    NATIONAL_DEX_APPLETUN,
    NATIONAL_DEX_DIPPLIN,
    NATIONAL_DEX_HYDRAPPLE,
    NATIONAL_DEX_SILICOBRA,
    NATIONAL_DEX_SANDACONDA,
    NATIONAL_DEX_CRAMORANT,
    NATIONAL_DEX_ARROKUDA,
    NATIONAL_DEX_BARRASKEWDA,
    NATIONAL_DEX_TOXEL,
    NATIONAL_DEX_TOXTRICITY,
    NATIONAL_DEX_SIZZLIPEDE,
    NATIONAL_DEX_CENTISKORCH,
    NATIONAL_DEX_HATENNA,
    NATIONAL_DEX_HATTREM,
    NATIONAL_DEX_HATTERENE,
    NATIONAL_DEX_FALINKS,
    NATIONAL_DEX_SNOM,
    NATIONAL_DEX_FROSMOTH,
    NATIONAL_DEX_STONJOURNER,
    NATIONAL_DEX_CUFANT,
    NATIONAL_DEX_COPPERAJAH,
    NATIONAL_DEX_DRACOZOLT,
    NATIONAL_DEX_ARCTOZOLT,
    NATIONAL_DEX_DRACOVISH,
    NATIONAL_DEX_ARCTOVISH,
    NATIONAL_DEX_DREEPY,
    NATIONAL_DEX_DRAKLOAK,
    NATIONAL_DEX_DRAGAPULT,
    NATIONAL_DEX_KUBFU,
    NATIONAL_DEX_URSHIFU,
    NATIONAL_DEX_REGIELEKI,
    NATIONAL_DEX_REGIDRAGO,
    NATIONAL_DEX_ENAMORUS,
    NATIONAL_DEX_NACLI,
    NATIONAL_DEX_NACLSTACK,
    NATIONAL_DEX_GARGANACL,
    NATIONAL_DEX_CHARCADET,
    NATIONAL_DEX_ARMAROUGE,
    NATIONAL_DEX_CERULEDGE,
    NATIONAL_DEX_SHROODLE,
    NATIONAL_DEX_GRAFAIAI,
    NATIONAL_DEX_BRAMBLIN,
    NATIONAL_DEX_BRAMBLEGHAST,
    NATIONAL_DEX_TOEDSCOOL,
    NATIONAL_DEX_TOEDSCRUEL,
    NATIONAL_DEX_TINKATINK,
    NATIONAL_DEX_TINKATUFF,
    NATIONAL_DEX_TINKATON,
    NATIONAL_DEX_WIGLETT,
    NATIONAL_DEX_WUGTRIO,
    NATIONAL_DEX_ORTHWORM,
    NATIONAL_DEX_GREAT_TUSK,
    NATIONAL_DEX_SCREAM_TAIL,
    NATIONAL_DEX_BRUTE_BONNET,
    NATIONAL_DEX_FLUTTER_MANE,
    NATIONAL_DEX_SLITHER_WING,
    NATIONAL_DEX_SANDY_SHOCKS,
    NATIONAL_DEX_FRIGIBAX,
    NATIONAL_DEX_ARCTIBAX,
    NATIONAL_DEX_BAXCALIBUR,
    NATIONAL_DEX_WO_CHIEN,
    NATIONAL_DEX_CHIEN_PAO,
    NATIONAL_DEX_TING_LU,
    NATIONAL_DEX_CHI_YU,
    NATIONAL_DEX_ROARING_MOON,
    NATIONAL_DEX_WALKING_WAKE,
    NATIONAL_DEX_GOUGING_FIRE,
    NATIONAL_DEX_RAGING_BOLT,
    // Megaten
    NATIONAL_DEX_DEMIFIEND,
    NATIONAL_DEX_MATADOR,
    NATIONAL_DEX_DAISOUJOU,
    NATIONAL_DEX_HELL_BIKER,
    NATIONAL_DEX_BLACK_RIDER,
    NATIONAL_DEX_WHITE_RIDER,
    NATIONAL_DEX_RED_RIDER,
    NATIONAL_DEX_PALE_RIDER,
    NATIONAL_DEX_MOTHER_HARLOT,
    NATIONAL_DEX_TRUMPETER,
    NATIONAL_DEX_PIXIE_DF,
    NATIONAL_DEX_JACK_FROST_DF,
    NATIONAL_DEX_CERBERUS_DF,
    NATIONAL_DEX_THOR_DF,
    NATIONAL_DEX_CU_CHULAINN_DF,
    NATIONAL_DEX_PARVATI_DF,
    NATIONAL_DEX_GIRIMEKHALA_DF,
    NATIONAL_DEX_NAAMAH,
    NATIONAL_DEX_EISHETH,
    NATIONAL_DEX_AGRAT,
    NATIONAL_DEX_LILITH,
    NATIONAL_DEX_SURT,
    NATIONAL_DEX_KING_FROST,
    NATIONAL_DEX_JATAYU,
    NATIONAL_DEX_SETH,
    NATIONAL_DEX_DANU,
    NATIONAL_DEX_ALICE,
    NATIONAL_DEX_SIEGFRIED,
    NATIONAL_DEX_ZEUS,
    NATIONAL_DEX_SHIVA,
    NATIONAL_DEX_SANDALPHON,
    NATIONAL_DEX_KOHRYU,
    NATIONAL_DEX_METATRON,
    NATIONAL_DEX_LUCIFER,
    NATIONAL_DEX_MARA,
    NATIONAL_DEX_NEKOMATA, 
    NATIONAL_DEX_AZUMI, 
    NATIONAL_DEX_URIEL,  
    NATIONAL_DEX_RAPHAEL,  
    NATIONAL_DEX_GABRIEL,
    NATIONAL_DEX_MICHAEL,
    NATIONAL_DEX_SUSANOO,
    NATIONAL_DEX_KONOHANA_SAKUYA,
    NATIONAL_DEX_BLACK_FROST,
    NATIONAL_DEX_ODIN,
    NATIONAL_DEX_BELIAL,
    NATIONAL_DEX_LUCIFUGE,
    NATIONAL_DEX_BEELZEBUB,
    NATIONAL_DEX_BELBERITH,
    NATIONAL_DEX_JEZEBEL,
    NATIONAL_DEX_NAHOBINO,
    NATIONAL_DEX_NAHOBEEHO,
    NATIONAL_DEX_PYRO_JACK,
    NATIONAL_DEX_NAPAEA,
    NATIONAL_DEX_MINOTAUR,
    NATIONAL_DEX_BAPHOMET,
    NATIONAL_DEX_VIRTUE,
    NATIONAL_DEX_THRONE,
    NATIONAL_DEX_LOA,
    NATIONAL_DEX_DAGDA,
    NATIONAL_DEX_MASTEMA,
    NATIONAL_DEX_YURLUNGUR,
    NATIONAL_DEX_POWER,
    NATIONAL_DEX_ANGEL,
    NATIONAL_DEX_MELCHIZEDEK,
    NATIONAL_DEX_NAGA,
    NATIONAL_DEX_MEDUSA,
    NATIONAL_DEX_SATAN_BLUE,
    NATIONAL_DEX_FROST_ACE,
    NATIONAL_DEX_DEMONEEHO,
    NATIONAL_DEX_ARAHABAKI,
    NATIONAL_DEX_MERMAID,
    NATIONAL_DEX_CLEOPATRA,
    NATIONAL_DEX_OBERON,
    NATIONAL_DEX_TITANIA,
    NATIONAL_DEX_HIGH_PIXIE,
    NATIONAL_DEX_SCATHACH,
    NATIONAL_DEX_MASAKADO_IV,
    NATIONAL_DEX_TAIRA_NO_MASAKADO,
    NATIONAL_DEX_JIKOKUTEN,
    NATIONAL_DEX_KOMOKUTEN,
    NATIONAL_DEX_BISHAMONTEN,
    NATIONAL_DEX_ZOUCHOUTEN,
    NATIONAL_DEX_ZHEN,
    NATIONAL_DEX_ZHU_TUN_SHE,
    NATIONAL_DEX_YATAGARASU,
    NATIONAL_DEX_WENDIGO,
    NATIONAL_DEX_VISHNU,
    NATIONAL_DEX_VASUKI,
    NATIONAL_DEX_THUNDERBIRD,
    NATIONAL_DEX_MOTHMAN,
    NATIONAL_DEX_THOTH,
    NATIONAL_DEX_TAKE_MINAKATA,
    NATIONAL_DEX_SLIME,
    NATIONAL_DEX_SRAOSHA,
    NATIONAL_DEX_SILKY,
    NATIONAL_DEX_SANDMAN,
    NATIONAL_DEX_SAMAEL,
    NATIONAL_DEX_RANGDA,
    NATIONAL_DEX_BARONG,
    NATIONAL_DEX_PRETA,
    NATIONAL_DEX_PISACA,
    NATIONAL_DEX_PEALLAIDH,
    NATIONAL_DEX_OSE,
    NATIONAL_DEX_OUROBOROS,
    NATIONAL_DEX_OROCHI,
    NATIONAL_DEX_ORTHRUS,
    NATIONAL_DEX_ONI,
    NATIONAL_DEX_ONGYO_KI,
    NATIONAL_DEX_KIN_KI,
    NATIONAL_DEX_FUU_KI,
    NATIONAL_DEX_SUI_KI,
    NATIONAL_DEX_NORN,
    NATIONAL_DEX_CLOTHO,
    NATIONAL_DEX_ATROPOS,
    NATIONAL_DEX_LACHESIS,
    NATIONAL_DEX_AME_NO_UZUME,
    NATIONAL_DEX_ALILAT,
    NATIONAL_DEX_OKUNINUSHI,
    NATIONAL_DEX_BALDUR,
    NATIONAL_DEX_PIXIE, 
    NATIONAL_DEX_JACK_FROST,
    NATIONAL_DEX_CERBERUS,
    NATIONAL_DEX_THOR,
    NATIONAL_DEX_CU_CHULAINN, 
    NATIONAL_DEX_PARVATI,
    NATIONAL_DEX_GIRIMEKHALA, 
    NATIONAL_DEX_SETANTA, 
    NATIONAL_DEX_KAIWAN, 
    NATIONAL_DEX_DECARABRIA, 
    NATIONAL_DEX_TAOTIE, 
    NATIONAL_DEX_NYAMI_NYAMI, 
    NATIONAL_DEX_MEPHISTO, 
    NATIONAL_DEX_HALPHAS, 
    NATIONAL_DEX_MOMONOFU, 
    NATIONAL_DEX_TURDAK,
    NATIONAL_DEX_SATAN_IV,
    NATIONAL_DEX_FORNEUS,
    NATIONAL_DEX_NIDHOGGR,
    NATIONAL_DEX_SKADI,
    NATIONAL_DEX_HORUS,
    NATIONAL_DEX_KRISHNA,
    NATIONAL_DEX_LEGION,
    NATIONAL_DEX_KURAMA_TENGU,
    NATIONAL_DEX_INCUBUS, 
    NATIONAL_DEX_DEMETER,
    NATIONAL_DEX_MANDRAKE,
};

#define JOHTO_DEX_COUNT     NATIONAL_DEX_CELEBI

#if P_GEN_9_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MANDRAKE
#elif P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ENAMORUS
#elif P_HISUIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_OVERQWIL
#elif P_GEN_8_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_URSALUNA
#elif P_GALARIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_RUNERIGUS

#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL

#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_6_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SYLVEON

#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT

#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#elif P_GEN_4_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_FROSLASS

#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

#if P_NEW_EVOS_IN_REGIONAL_DEX
#define HOENN_DEX_IF(config, ...) CAT(HOENN_DEX_IF_, config)(__VA_ARGS__)
#define HOENN_DEX_IF_0(...)
#define HOENN_DEX_IF_1(...) __VA_ARGS__
#else
#define HOENN_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_HOENN_DEX_ORDER(F) \
    F(TREECKO) \
    F(GROVYLE) \
    F(SCEPTILE) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(MUDKIP) \
    F(MARSHTOMP) \
    F(SWAMPERT) \
    F(POOCHYENA) \
    F(MIGHTYENA) \
    F(ZIGZAGOON) \
    F(LINOONE) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(OBSTAGOON)) \
    F(WURMPLE) \
    F(SILCOON) \
    F(BEAUTIFLY) \
    F(CASCOON) \
    F(DUSTOX) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(TAILLOW) \
    F(SWELLOW) \
    F(WINGULL) \
    F(PELIPPER) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(GALLADE)) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(SLAKOTH) \
    F(VIGOROTH) \
    F(SLAKING) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(NINCADA) \
    F(NINJASK) \
    F(SHEDINJA) \
    F(WHISMUR) \
    F(LOUDRED) \
    F(EXPLOUD) \
    F(MAKUHITA) \
    F(HARIYAMA) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(AZURILL) \
    F(MARILL) \
    F(AZUMARILL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(NOSEPASS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(PROBOPASS)) \
    F(SKITTY) \
    F(DELCATTY) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(CROBAT) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(SABLEYE) \
    F(MAWILE) \
    F(ARON) \
    F(LAIRON) \
    F(AGGRON) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(MEDITITE) \
    F(MEDICHAM) \
    F(ELECTRIKE) \
    F(MANECTRIC) \
    F(PLUSLE) \
    F(MINUN) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(VOLBEAT) \
    F(ILLUMISE) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    F(BELLOSSOM) \
    F(DODUO) \
    F(DODRIO) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(BUDEW)) \
    F(ROSELIA) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(ROSERADE)) \
    F(GULPIN) \
    F(SWALOT) \
    F(CARVANHA) \
    F(SHARPEDO) \
    F(WAILMER) \
    F(WAILORD) \
    F(NUMEL) \
    F(CAMERUPT) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(TORKOAL) \
    F(GRIMER) \
    F(MUK) \
    F(KOFFING) \
    F(WEEZING) \
    F(SPOINK) \
    F(GRUMPIG) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(SPINDA) \
    F(SKARMORY) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(SWABLU) \
    F(ALTARIA) \
    F(ZANGOOSE) \
    F(SEVIPER) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BARBOACH) \
    F(WHISCASH) \
    F(CORPHISH) \
    F(CRAWDAUNT) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(LILEEP) \
    F(CRADILY) \
    F(ANORITH) \
    F(ARMALDO) \
    F(IGGLYBUFF) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(STARYU) \
    F(STARMIE) \
    F(KECLEON) \
    F(SHUPPET) \
    F(BANETTE) \
    F(DUSKULL) \
    F(DUSCLOPS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(DUSKNOIR)) \
    F(TROPIUS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(CHINGLING)) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(VULPIX) \
    F(NINETALES) \
    F(PICHU) \
    F(PIKACHU) \
    F(RAICHU) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(WYNAUT) \
    F(WOBBUFFET) \
    F(NATU) \
    F(XATU) \
    F(GIRAFARIG) \
    HOENN_DEX_IF(P_GEN_9_CROSS_EVOS, F(FARIGIRAF)) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PINSIR) \
    F(HERACROSS) \
    F(RHYHORN) \
    F(RHYDON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    F(SNORUNT) \
    F(GLALIE) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(FROSLASS)) \
    F(SPHEAL) \
    F(SEALEO) \
    F(WALREIN) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(RELICANTH) \
    F(CORSOLA) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(CURSOLA)) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(LUVDISC) \
    F(HORSEA) \
    F(SEADRA) \
    F(KINGDRA) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(LATIAS) \
    F(LATIOS) \
    F(KYOGRE) \
    F(GROUDON) \
    F(RAYQUAZA) \
    F(JIRACHI) \
    F(DEOXYS)

// Hoenn Pokédex order
enum HoennDexOrder
{
    HOENN_DEX_NONE,
    #define HOENN_DEX_ENUM(name) HOENN_DEX_ ##name,
    FOREACH_SPECIES_IN_HOENN_DEX_ORDER(HOENN_DEX_ENUM)
    #undef HOENN_DEX_ENUM

    HOENN_DEX_BULBASAUR,
    HOENN_DEX_IVYSAUR,
    HOENN_DEX_VENUSAUR,
    HOENN_DEX_CHARMANDER,
    HOENN_DEX_CHARMELEON,
    HOENN_DEX_CHARIZARD,
    HOENN_DEX_SQUIRTLE,
    HOENN_DEX_WARTORTLE,
    HOENN_DEX_BLASTOISE,
    HOENN_DEX_PIDGEY,
    HOENN_DEX_PIDGEOTTO,
    HOENN_DEX_PIDGEOT,
    HOENN_DEX_WEEDLE,
    HOENN_DEX_KAKUNA,
    HOENN_DEX_BEEDRILL,
    HOENN_DEX_RATTATA,
    HOENN_DEX_RATICATE,
    HOENN_DEX_SPEAROW,
    HOENN_DEX_FEAROW,
    HOENN_DEX_EKANS,
    HOENN_DEX_ARBOK,
    HOENN_DEX_SANDSHREW,
    HOENN_DEX_SANDSLASH,
    HOENN_DEX_NIDORAN_F,
    HOENN_DEX_NIDORINA,
    HOENN_DEX_NIDOQUEEN,
    HOENN_DEX_NIDORAN_M,
    HOENN_DEX_NIDORINO,
    HOENN_DEX_NIDOKING,
    HOENN_DEX_ZUBAT,
    HOENN_DEX_GOLBAT,
    HOENN_DEX_CROBAT,
    HOENN_DEX_PARAS,
    HOENN_DEX_PARASECT,
    HOENN_DEX_DIGLETT,
    HOENN_DEX_DUGTRIO,
    HOENN_DEX_MEOWTH,
    HOENN_DEX_PERSIAN,
    HOENN_DEX_PERRSERKER,
    HOENN_DEX_MANKEY,
    HOENN_DEX_PRIMEAPE,
    HOENN_DEX_ANNIHILAPE,
    HOENN_DEX_GROWLITHE,
    HOENN_DEX_ARCANINE,
    HOENN_DEX_POLIWAG,
    HOENN_DEX_POLIWHIRL,
    HOENN_DEX_POLIWRATH,
    HOENN_DEX_POLITOED,
    HOENN_DEX_MACHOP,
    HOENN_DEX_MACHOKE,
    HOENN_DEX_MACHAMP,
    HOENN_DEX_BELLSPROUT,
    HOENN_DEX_WEEPINBELL,
    HOENN_DEX_VICTREEBEL,
    HOENN_DEX_GEODUDE,
    HOENN_DEX_GRAVELER,
    HOENN_DEX_GOLEM,
    HOENN_DEX_PONYTA,
    HOENN_DEX_RAPIDASH,
    HOENN_DEX_SLOWPOKE,
    HOENN_DEX_SLOWBRO,
    HOENN_DEX_SLOWKING,
    HOENN_DEX_FARFETCHD,
    HOENN_DEX_SIRFETCHD,
    HOENN_DEX_DODUO,
    HOENN_DEX_DODRIO,
    HOENN_DEX_GASTLY,
    HOENN_DEX_HAUNTER,
    HOENN_DEX_GENGAR,
    HOENN_DEX_ONIX,
    HOENN_DEX_STEELIX,
    HOENN_DEX_CUBONE,
    HOENN_DEX_MAROWAK,
    HOENN_DEX_TYROGUE,
    HOENN_DEX_HITMONLEE,
    HOENN_DEX_HITMONCHAN,
    HOENN_DEX_HITMONTOP,
    HOENN_DEX_RHYHORN,
    HOENN_DEX_RHYDON,
    HOENN_DEX_RHYPERIOR,
    HOENN_DEX_CHANSEY,
    HOENN_DEX_KANGASKHAN,
    HOENN_DEX_HORSEA,
    HOENN_DEX_SEADRA,
    HOENN_DEX_KINGDRA,
    HOENN_DEX_SCYTHER,
    HOENN_DEX_SCIZOR,
    HOENN_DEX_KLEAVOR,
    HOENN_DEX_MAGBY,
    HOENN_DEX_MAGMAR,
    HOENN_DEX_MAGMORTAR,
    HOENN_DEX_TAUROS,
    HOENN_DEX_MAGIKARP,
    HOENN_DEX_GYARADOS,
    HOENN_DEX_OMANYTE,
    HOENN_DEX_OMASTAR,
    HOENN_DEX_KABUTO,
    HOENN_DEX_KABUTOPS,
    HOENN_DEX_AERODACTYL,
    HOENN_DEX_MUNCHLAX,
    HOENN_DEX_SNORLAX,
    HOENN_DEX_DRATINI,
    HOENN_DEX_DRAGONAIR,
    HOENN_DEX_DRAGONITE,
    HOENN_DEX_MEW,
    HOENN_DEX_CHIKORITA,
    HOENN_DEX_BAYLEEF,
    HOENN_DEX_MEGANIUM,
    HOENN_DEX_CYNDAQUIL,
    HOENN_DEX_QUILAVA,
    HOENN_DEX_TYPHLOSION,
    HOENN_DEX_TOTODILE,
    HOENN_DEX_CROCONAW,
    HOENN_DEX_FERALIGATR,
    HOENN_DEX_SENTRET,
    HOENN_DEX_FURRET,
    HOENN_DEX_HOOTHOOT,
    HOENN_DEX_NOCTOWL,
    HOENN_DEX_SPINARAK,
    HOENN_DEX_ARIADOS,
    HOENN_DEX_TOGEPI,
    HOENN_DEX_TOGETIC,
    HOENN_DEX_TOGEKISS,
    HOENN_DEX_NATU,
    HOENN_DEX_XATU,
    HOENN_DEX_MAREEP,
    HOENN_DEX_FLAAFFY,
    HOENN_DEX_AMPHAROS,
    HOENN_DEX_BONSLY,
    HOENN_DEX_SUDOWOODO,
    HOENN_DEX_HOPPIP,
    HOENN_DEX_SKIPLOOM,
    HOENN_DEX_JUMPLUFF,
    HOENN_DEX_AIPOM,
    HOENN_DEX_AMBIPOM,
    HOENN_DEX_SUNKERN,
    HOENN_DEX_SUNFLORA,
    HOENN_DEX_YANMA,
    HOENN_DEX_YANMEGA,
    HOENN_DEX_WOOPER,
    HOENN_DEX_QUAGSIRE,
    HOENN_DEX_CLODSIRE,
    HOENN_DEX_UNOWN,
    HOENN_DEX_MURKROW,
    HOENN_DEX_HONCHKROW,
    HOENN_DEX_GIRAFARIG,
    HOENN_DEX_FARIGIRAF,
    HOENN_DEX_PINECO,
    HOENN_DEX_FORRETRESS,
    HOENN_DEX_DUNSPARCE,
    HOENN_DEX_DUDUNSPARCE,
    HOENN_DEX_GLIGAR,
    HOENN_DEX_GLISCOR,
    HOENN_DEX_QWILFISH,
    HOENN_DEX_OVERQWIL,
    HOENN_DEX_SHUCKLE,
    HOENN_DEX_HERACROSS,
    HOENN_DEX_SNEASEL,
    HOENN_DEX_SNEASLER,
    HOENN_DEX_SLUGMA,
    HOENN_DEX_MAGCARGO,
    HOENN_DEX_CORSOLA,
    HOENN_DEX_CURSOLA,
    HOENN_DEX_REMORAID,
    HOENN_DEX_OCTILLERY,
    HOENN_DEX_HOUNDOUR,
    HOENN_DEX_HOUNDOOM,
    HOENN_DEX_PHANPY,
    HOENN_DEX_DONPHAN,
    HOENN_DEX_STANTLER,
    HOENN_DEX_WYRDEER,
    HOENN_DEX_RAIKOU,
    HOENN_DEX_ENTEI,
    HOENN_DEX_SUICUNE,
    HOENN_DEX_LARVITAR,
    HOENN_DEX_PUPITAR,
    HOENN_DEX_TYRANITAR,
    HOENN_DEX_CELEBI,
    HOENN_DEX_TREECKO,
    HOENN_DEX_GROVYLE,
    HOENN_DEX_SCEPTILE,
    HOENN_DEX_TORCHIC,
    HOENN_DEX_COMBUSKEN,
    HOENN_DEX_BLAZIKEN,
    HOENN_DEX_MUDKIP,
    HOENN_DEX_MARSHTOMP,
    HOENN_DEX_SWAMPERT,
    HOENN_DEX_POOCHYENA,
    HOENN_DEX_MIGHTYENA,
    HOENN_DEX_ZIGZAGOON,
    HOENN_DEX_LINOONE,
    HOENN_DEX_OBSTAGOON,
    HOENN_DEX_LOTAD,
    HOENN_DEX_LOMBRE,
    HOENN_DEX_LUDICOLO,
    HOENN_DEX_SEEDOT,
    HOENN_DEX_NUZLEAF,
    HOENN_DEX_SHIFTRY,
    HOENN_DEX_TAILLOW,
    HOENN_DEX_SWELLOW,
    HOENN_DEX_RALTS,
    HOENN_DEX_KIRLIA,
    HOENN_DEX_GARDEVOIR,
    HOENN_DEX_GALLADE,
    HOENN_DEX_SURSKIT,
    HOENN_DEX_MASQUERAIN,
    HOENN_DEX_SHROOMISH,
    HOENN_DEX_BRELOOM,
    HOENN_DEX_SLAKOTH,
    HOENN_DEX_VIGOROTH,
    HOENN_DEX_SLAKING,
    HOENN_DEX_NINCADA,
    HOENN_DEX_NINJASK,
    HOENN_DEX_SHEDINJA,
    HOENN_DEX_WHISMUR,
    HOENN_DEX_LOUDRED,
    HOENN_DEX_EXPLOUD,
    HOENN_DEX_MAKUHITA,
    HOENN_DEX_HARIYAMA,
    HOENN_DEX_AZURILL,
    HOENN_DEX_MARILL,
    HOENN_DEX_AZUMARILL,
    HOENN_DEX_NOSEPASS,
    HOENN_DEX_PROBOPASS,
    HOENN_DEX_SABLEYE,
    HOENN_DEX_MAWILE,
    HOENN_DEX_ARON,
    HOENN_DEX_LAIRON,
    HOENN_DEX_AGGRON,
    HOENN_DEX_ELECTRIKE,
    HOENN_DEX_MANECTRIC,
    HOENN_DEX_VOLBEAT,
    HOENN_DEX_ILLUMISE,
    HOENN_DEX_BUDEW,
    HOENN_DEX_ROSELIA,
    HOENN_DEX_ROSERADE,
    HOENN_DEX_GULPIN,
    HOENN_DEX_SWALOT,
    HOENN_DEX_CARVANHA,
    HOENN_DEX_SHARPEDO,
    HOENN_DEX_WAILMER,
    HOENN_DEX_WAILORD,
    HOENN_DEX_NUMEL,
    HOENN_DEX_CAMERUPT,
    HOENN_DEX_TRAPINCH,
    HOENN_DEX_VIBRAVA,
    HOENN_DEX_FLYGON,
    HOENN_DEX_CACNEA,
    HOENN_DEX_CACTURNE,
    HOENN_DEX_SWABLU,
    HOENN_DEX_ALTARIA,
    HOENN_DEX_ZANGOOSE,
    HOENN_DEX_SEVIPER,
    HOENN_DEX_LUNATONE,
    HOENN_DEX_SOLROCK,
    HOENN_DEX_BARBOACH,
    HOENN_DEX_WHISCASH,
    HOENN_DEX_BALTOY,
    HOENN_DEX_CLAYDOL,
    HOENN_DEX_LILEEP,
    HOENN_DEX_CRADILY,
    HOENN_DEX_ANORITH,
    HOENN_DEX_ARMALDO,
    HOENN_DEX_FEEBAS,
    HOENN_DEX_MILOTIC,
    HOENN_DEX_KECLEON,
    HOENN_DEX_DUSKULL,
    HOENN_DEX_DUSCLOPS,
    HOENN_DEX_DUSKNOIR,
    HOENN_DEX_ABSOL,
    HOENN_DEX_SNORUNT,
    HOENN_DEX_GLALIE,
    HOENN_DEX_FROSLASS,
    HOENN_DEX_CLAMPERL,
    HOENN_DEX_GOREBYSS,
    HOENN_DEX_HUNTAIL,
    HOENN_DEX_RELICANTH,
    HOENN_DEX_BAGON,
    HOENN_DEX_SHELGON,
    HOENN_DEX_SALAMENCE,
    HOENN_DEX_BELDUM,
    HOENN_DEX_METANG,
    HOENN_DEX_METAGROSS,
    HOENN_DEX_REGIROCK,
    HOENN_DEX_REGICE,
    HOENN_DEX_REGISTEEL,
    HOENN_DEX_KYOGRE,
    HOENN_DEX_GROUDON,
    HOENN_DEX_RAYQUAZA,
    HOENN_DEX_DEOXYS,
    HOENN_DEX_TURTWIG,
    HOENN_DEX_GROTLE,
    HOENN_DEX_TORTERRA,
    HOENN_DEX_CHIMCHAR,
    HOENN_DEX_MONFERNO,
    HOENN_DEX_INFERNAPE,
    HOENN_DEX_PIPLUP,
    HOENN_DEX_PRINPLUP,
    HOENN_DEX_EMPOLEON,
    HOENN_DEX_STARLY,
    HOENN_DEX_STARAVIA,
    HOENN_DEX_STARAPTOR,
    HOENN_DEX_BIDOOF,
    HOENN_DEX_BIBAREL,
    HOENN_DEX_SHINX,
    HOENN_DEX_LUXIO,
    HOENN_DEX_LUXRAY,
    HOENN_DEX_CRANIDOS,
    HOENN_DEX_RAMPARDOS,
    HOENN_DEX_SHIELDON,
    HOENN_DEX_BASTIODON,
    HOENN_DEX_BURMY,
    HOENN_DEX_WORMADAM,
    HOENN_DEX_MOTHIM,
    HOENN_DEX_COMBEE,
    HOENN_DEX_VESPIQUEN,
    HOENN_DEX_BUIZEL,
    HOENN_DEX_FLOATZEL,
    HOENN_DEX_SHELLOS,
    HOENN_DEX_GASTRODON,
    HOENN_DEX_DRIFLOON,
    HOENN_DEX_DRIFBLIM,
    HOENN_DEX_BUNEARY,
    HOENN_DEX_LOPUNNY,
    HOENN_DEX_STUNKY,
    HOENN_DEX_SKUNTANK,
    HOENN_DEX_BRONZOR,
    HOENN_DEX_BRONZONG,
    HOENN_DEX_SPIRITOMB,
    HOENN_DEX_GIBLE,
    HOENN_DEX_GABITE,
    HOENN_DEX_GARCHOMP,
    HOENN_DEX_RIOLU,
    HOENN_DEX_LUCARIO,
    HOENN_DEX_HIPPOPOTAS,
    HOENN_DEX_HIPPOWDON,
    HOENN_DEX_SKORUPI,
    HOENN_DEX_DRAPION,
    HOENN_DEX_CROAGUNK,
    HOENN_DEX_TOXICROAK,
    HOENN_DEX_CARNIVINE,
    HOENN_DEX_FINNEON,
    HOENN_DEX_LUMINEON,
    HOENN_DEX_SNOVER,
    HOENN_DEX_ABOMASNOW,
    HOENN_DEX_UXIE,
    HOENN_DEX_MESPRIT,
    HOENN_DEX_AZELF,
    HOENN_DEX_DIALGA,
    HOENN_DEX_PALKIA,
    HOENN_DEX_REGIGIGAS,
    HOENN_DEX_GIRATINA,
    HOENN_DEX_CRESSELIA,
    HOENN_DEX_DARKRAI,
    HOENN_DEX_ARCEUS,
    HOENN_DEX_VICTINI,
    HOENN_DEX_PATRAT,
    HOENN_DEX_WATCHOG,
    HOENN_DEX_PURRLOIN,
    HOENN_DEX_LIEPARD,
    HOENN_DEX_PANSAGE,
    HOENN_DEX_SIMISAGE,
    HOENN_DEX_PANSEAR,
    HOENN_DEX_SIMISEAR,
    HOENN_DEX_PANPOUR,
    HOENN_DEX_SIMIPOUR,
    HOENN_DEX_BLITZLE,
    HOENN_DEX_ZEBSTRIKA,
    HOENN_DEX_ROGGENROLA,
    HOENN_DEX_BOLDORE,
    HOENN_DEX_GIGALITH,
    HOENN_DEX_DRILBUR,
    HOENN_DEX_EXCADRILL,
    HOENN_DEX_AUDINO,
    HOENN_DEX_TIMBURR,
    HOENN_DEX_GURDURR,
    HOENN_DEX_CONKELDURR,
    HOENN_DEX_TYMPOLE,
    HOENN_DEX_PALPITOAD,
    HOENN_DEX_SEISMITOAD,
    HOENN_DEX_THROH,
    HOENN_DEX_SAWK,
    HOENN_DEX_SEWADDLE,
    HOENN_DEX_SWADLOON,
    HOENN_DEX_LEAVANNY,
    HOENN_DEX_VENIPEDE,
    HOENN_DEX_WHIRLIPEDE,
    HOENN_DEX_SCOLIPEDE,
    HOENN_DEX_PETILIL,
    HOENN_DEX_LILLIGANT,
    HOENN_DEX_BASCULIN,
    HOENN_DEX_BASCULEGION,
    HOENN_DEX_SANDILE,
    HOENN_DEX_KROKOROK,
    HOENN_DEX_KROOKODILE,
    HOENN_DEX_DARUMAKA,
    HOENN_DEX_DARMANITAN,
    HOENN_DEX_MARACTUS,
    HOENN_DEX_DWEBBLE,
    HOENN_DEX_CRUSTLE,
    HOENN_DEX_SCRAGGY,
    HOENN_DEX_SCRAFTY,
    HOENN_DEX_SIGILYPH,
    HOENN_DEX_YAMASK,
    HOENN_DEX_RUNERIGUS,
    HOENN_DEX_TIRTOUGA,
    HOENN_DEX_CARRACOSTA,
    HOENN_DEX_ARCHEN,
    HOENN_DEX_ARCHEOPS,
    HOENN_DEX_ZORUA,
    HOENN_DEX_ZOROARK,
    HOENN_DEX_SOLOSIS,
    HOENN_DEX_DUOSION,
    HOENN_DEX_REUNICLUS,
    HOENN_DEX_KARRABLAST,
    HOENN_DEX_ESCAVALIER,
    HOENN_DEX_FOONGUS,
    HOENN_DEX_AMOONGUSS,
    HOENN_DEX_FRILLISH,
    HOENN_DEX_JELLICENT,
    HOENN_DEX_JOLTIK,
    HOENN_DEX_GALVANTULA,
    HOENN_DEX_FERROSEED,
    HOENN_DEX_FERROTHORN,
    HOENN_DEX_TYNAMO,
    HOENN_DEX_EELEKTRIK,
    HOENN_DEX_EELEKTROSS,
    HOENN_DEX_ELGYEM,
    HOENN_DEX_BEHEEYEM,
    HOENN_DEX_LITWICK,
    HOENN_DEX_LAMPENT,
    HOENN_DEX_CHANDELURE,
    HOENN_DEX_AXEW,
    HOENN_DEX_FRAXURE,
    HOENN_DEX_HAXORUS,
    HOENN_DEX_CRYOGONAL,
    HOENN_DEX_SHELMET,
    HOENN_DEX_ACCELGOR,
    HOENN_DEX_STUNFISK,
    HOENN_DEX_MIENFOO,
    HOENN_DEX_MIENSHAO,
    HOENN_DEX_DRUDDIGON,
    HOENN_DEX_GOLETT,
    HOENN_DEX_GOLURK,
    HOENN_DEX_PAWNIARD,
    HOENN_DEX_BISHARP,
    HOENN_DEX_KINGAMBIT,
    HOENN_DEX_RUFFLET,
    HOENN_DEX_BRAVIARY,
    HOENN_DEX_VULLABY,
    HOENN_DEX_MANDIBUZZ,
    HOENN_DEX_HEATMOR,
    HOENN_DEX_DURANT,
    HOENN_DEX_DEINO,
    HOENN_DEX_ZWEILOUS,
    HOENN_DEX_HYDREIGON,
    HOENN_DEX_LARVESTA,
    HOENN_DEX_VOLCARONA,
    HOENN_DEX_TORNADUS,
    HOENN_DEX_THUNDURUS,
    HOENN_DEX_RESHIRAM,
    HOENN_DEX_ZEKROM,
    HOENN_DEX_LANDORUS,
    HOENN_DEX_KYUREM,
    HOENN_DEX_GENESECT,
    HOENN_DEX_CHESPIN,
    HOENN_DEX_QUILLADIN,
    HOENN_DEX_CHESNAUGHT,
    HOENN_DEX_FENNEKIN,
    HOENN_DEX_BRAIXEN,
    HOENN_DEX_DELPHOX,
    HOENN_DEX_FROAKIE,
    HOENN_DEX_FROGADIER,
    HOENN_DEX_GRENINJA,
    HOENN_DEX_FLETCHLING,
    HOENN_DEX_FLETCHINDER,
    HOENN_DEX_TALONFLAME,
    HOENN_DEX_LITLEO,
    HOENN_DEX_PYROAR,
    HOENN_DEX_PANCHAM,
    HOENN_DEX_PANGORO,
    HOENN_DEX_ESPURR,
    HOENN_DEX_MEOWSTIC,
    HOENN_DEX_HONEDGE,
    HOENN_DEX_DOUBLADE,
    HOENN_DEX_AEGISLASH,
    HOENN_DEX_INKAY,
    HOENN_DEX_MALAMAR,
    HOENN_DEX_BINACLE,
    HOENN_DEX_BARBARACLE,
    HOENN_DEX_SKRELP,
    HOENN_DEX_DRAGALGE,
    HOENN_DEX_CLAUNCHER,
    HOENN_DEX_CLAWITZER,
    HOENN_DEX_TYRUNT,
    HOENN_DEX_TYRANTRUM,
    HOENN_DEX_AMAURA,
    HOENN_DEX_AURORUS,
    HOENN_DEX_CARBINK,
    HOENN_DEX_GOOMY,
    HOENN_DEX_SLIGGOO,
    HOENN_DEX_GOODRA,
    HOENN_DEX_PHANTUMP,
    HOENN_DEX_TREVENANT,
    HOENN_DEX_PUMPKABOO,
    HOENN_DEX_GOURGEIST,
    HOENN_DEX_NOIBAT,
    HOENN_DEX_NOIVERN,
    HOENN_DEX_ZYGARDE,
    HOENN_DEX_DIANCIE,
    HOENN_DEX_VOLCANION,
    HOENN_DEX_ROWLET,
    HOENN_DEX_DARTRIX,
    HOENN_DEX_DECIDUEYE,
    HOENN_DEX_LITTEN,
    HOENN_DEX_TORRACAT,
    HOENN_DEX_INCINEROAR,
    HOENN_DEX_POPPLIO,
    HOENN_DEX_BRIONNE,
    HOENN_DEX_PRIMARINA,
    HOENN_DEX_CRABRAWLER,
    HOENN_DEX_CRABOMINABLE,
    HOENN_DEX_ROCKRUFF,
    HOENN_DEX_LYCANROC,
    HOENN_DEX_WISHIWASHI,
    HOENN_DEX_MAREANIE,
    HOENN_DEX_TOXAPEX,
    HOENN_DEX_MUDBRAY,
    HOENN_DEX_MUDSDALE,
    HOENN_DEX_DEWPIDER,
    HOENN_DEX_ARAQUANID,
    HOENN_DEX_FOMANTIS,
    HOENN_DEX_LURANTIS,
    HOENN_DEX_MORELULL,
    HOENN_DEX_SHIINOTIC,
    HOENN_DEX_SALANDIT,
    HOENN_DEX_SALAZZLE,
    HOENN_DEX_STUFFUL,
    HOENN_DEX_BEWEAR,
    HOENN_DEX_BOUNSWEET,
    HOENN_DEX_STEENEE,
    HOENN_DEX_TSAREENA,
    HOENN_DEX_WIMPOD,
    HOENN_DEX_GOLISOPOD,
    HOENN_DEX_TYPE_NULL,
    HOENN_DEX_SILVALLY,
    HOENN_DEX_KOMALA,
    HOENN_DEX_TURTONATOR,
    HOENN_DEX_TOGEDEMARU,
    HOENN_DEX_BRUXISH,
    HOENN_DEX_DRAMPA,
    HOENN_DEX_JANGMO_O,
    HOENN_DEX_HAKAMO_O,
    HOENN_DEX_KOMMO_O,
    HOENN_DEX_COSMOG,
    HOENN_DEX_COSMOEM,
    HOENN_DEX_LUNALA,
    HOENN_DEX_SOLGALEO,
    HOENN_DEX_NIHILEGO,
    HOENN_DEX_BUZZWOLE,
    HOENN_DEX_PHEROMOSA,
    HOENN_DEX_XURKITREE,
    HOENN_DEX_CELESTEELA,
    HOENN_DEX_KARTANA,
    HOENN_DEX_GUZZLORD,
    HOENN_DEX_NECROZMA,
    HOENN_DEX_POIPOLE,
    HOENN_DEX_NAGANADEL,
    HOENN_DEX_STAKATAKA,
    HOENN_DEX_BLACEPHALON,
    HOENN_DEX_ZERAORA,
    HOENN_DEX_ROOKIDEE,
    HOENN_DEX_CORVISQUIRE,
    HOENN_DEX_CORVIKNIGHT,
    HOENN_DEX_BLIPBUG,
    HOENN_DEX_DOTTLER,
    HOENN_DEX_ORBEETLE,
    HOENN_DEX_GOSSIFLEUR,
    HOENN_DEX_ELDEGOSS,
    HOENN_DEX_CHEWTLE,
    HOENN_DEX_DREDNAW,
    HOENN_DEX_ROLYCOLY,
    HOENN_DEX_CARKOL,
    HOENN_DEX_COALOSSAL,
    HOENN_DEX_APPLIN,
    HOENN_DEX_FLAPPLE,
    HOENN_DEX_APPLETUN,
    HOENN_DEX_DIPPLIN,
    HOENN_DEX_HYDRAPPLE,
    HOENN_DEX_SILICOBRA,
    HOENN_DEX_SANDACONDA,
    HOENN_DEX_CRAMORANT,
    HOENN_DEX_ARROKUDA,
    HOENN_DEX_BARRASKEWDA,
    HOENN_DEX_TOXEL,
    HOENN_DEX_TOXTRICITY,
    HOENN_DEX_SIZZLIPEDE,
    HOENN_DEX_CENTISKORCH,
    HOENN_DEX_HATENNA,
    HOENN_DEX_HATTREM,
    HOENN_DEX_HATTERENE,
    HOENN_DEX_FALINKS,
    HOENN_DEX_SNOM,
    HOENN_DEX_FROSMOTH,
    HOENN_DEX_STONJOURNER,
    HOENN_DEX_CUFANT,
    HOENN_DEX_COPPERAJAH,
    HOENN_DEX_DRACOZOLT,
    HOENN_DEX_ARCTOZOLT,
    HOENN_DEX_DRACOVISH,
    HOENN_DEX_ARCTOVISH,
    HOENN_DEX_DREEPY,
    HOENN_DEX_DRAKLOAK,
    HOENN_DEX_DRAGAPULT,
    HOENN_DEX_KUBFU,
    HOENN_DEX_URSHIFU,
    HOENN_DEX_REGIELEKI,
    HOENN_DEX_REGIDRAGO,
    HOENN_DEX_ENAMORUS,
    HOENN_DEX_NACLI,
    HOENN_DEX_NACLSTACK,
    HOENN_DEX_GARGANACL,
    HOENN_DEX_CHARCADET,
    HOENN_DEX_ARMAROUGE,
    HOENN_DEX_CERULEDGE,
    HOENN_DEX_SHROODLE,
    HOENN_DEX_GRAFAIAI,
    HOENN_DEX_BRAMBLIN,
    HOENN_DEX_BRAMBLEGHAST,
    HOENN_DEX_TOEDSCOOL,
    HOENN_DEX_TOEDSCRUEL,
    HOENN_DEX_TINKATINK,
    HOENN_DEX_TINKATUFF,
    HOENN_DEX_TINKATON,
    HOENN_DEX_WIGLETT,
    HOENN_DEX_WUGTRIO,
    HOENN_DEX_ORTHWORM,
    HOENN_DEX_GREAT_TUSK,
    HOENN_DEX_SCREAM_TAIL,
    HOENN_DEX_BRUTE_BONNET,
    HOENN_DEX_FLUTTER_MANE,
    HOENN_DEX_SLITHER_WING,
    HOENN_DEX_SANDY_SHOCKS,
    HOENN_DEX_FRIGIBAX,
    HOENN_DEX_ARCTIBAX,
    HOENN_DEX_BAXCALIBUR,
    HOENN_DEX_WO_CHIEN,
    HOENN_DEX_CHIEN_PAO,
    HOENN_DEX_TING_LU,
    HOENN_DEX_CHI_YU,
    HOENN_DEX_ROARING_MOON,
    HOENN_DEX_WALKING_WAKE,
    HOENN_DEX_GOUGING_FIRE,
    HOENN_DEX_RAGING_BOLT,
};


// Kanto Pokedex order
enum KantoDexOrder
#if P_NEW_EVOS_IN_REGIONAL_DEX
#define KANTO_DEX_IF(config, ...) CAT(KANTO_DEX_IF_, config)(__VA_ARGS__)
#define KANTO_DEX_IF_0(...)
#define KANTO_DEX_IF_1(...) __VA_ARGS__
#else
#define KANTO_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_KANTO_DEX_ORDER(F) \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(CHARMANDER) \
    F(CHARMELEON) \
    F(CHARIZARD) \
    F(SQUIRTLE) \
    F(WARTORTLE) \
    F(BLASTOISE) \
    F(CATERPIE) \
    F(METAPOD) \
    F(BUTTERFREE) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(PIDGEY) \
    F(PIDGEOTTO) \
    F(PIDGEOT) \
    F(RATTATA) \
    F(RATICATE) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PICHU)) \
    F(PIKACHU) \
    F(RAICHU) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(NIDORAN_F) \
    F(NIDORINA) \
    F(NIDOQUEEN) \
    F(NIDORAN_M) \
    F(NIDORINO) \
    F(NIDOKING) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CLEFFA)) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(IGGLYBUFF)) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CROBAT)) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BELLOSSOM)) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(DIGLETT) \
    F(DUGTRIO) \
    F(MEOWTH) \
    F(PERSIAN) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(PERRSERKER)) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(MANKEY) \
    F(PRIMEAPE) \
    KANTO_DEX_IF(P_GEN_9_CROSS_EVOS, F(ANNIHILAPE)) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(POLIWAG) \
    F(POLIWHIRL) \
    F(POLIWRATH) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(POLITOED)) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(BELLSPROUT) \
    F(WEEPINBELL) \
    F(VICTREEBEL) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SLOWKING)) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(FARFETCHD) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(SIRFETCHD)) \
    F(DODUO) \
    F(DODRIO) \
    F(SEEL) \
    F(DEWGONG) \
    F(GRIMER) \
    F(MUK) \
    F(SHELLDER) \
    F(CLOYSTER) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(ONIX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(STEELIX)) \
    F(DROWZEE) \
    F(HYPNO) \
    F(KRABBY) \
    F(KINGLER) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(EXEGGCUTE) \
    F(EXEGGUTOR) \
    F(CUBONE) \
    F(MAROWAK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(TYROGUE)) \
    F(HITMONLEE) \
    F(HITMONCHAN) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(HITMONTOP)) \
    F(LICKITUNG) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LICKILICKY)) \
    F(KOFFING) \
    F(WEEZING) \
    F(RHYHORN) \
    F(RHYDON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(HAPPINY)) \
    F(CHANSEY) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BLISSEY)) \
    F(TANGELA) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(TANGROWTH)) \
    F(KANGASKHAN) \
    F(HORSEA) \
    F(SEADRA) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(KINGDRA)) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MIME_JR)) \
    F(MR_MIME) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(MR_RIME)) \
    F(SCYTHER) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SCIZOR)) \
    KANTO_DEX_IF(P_GEN_8_CROSS_EVOS, F(KLEAVOR)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SMOOCHUM)) \
    F(JYNX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ELEKID)) \
    F(ELECTABUZZ) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(ELECTIVIRE)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(MAGBY)) \
    F(MAGMAR) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGMORTAR)) \
    F(PINSIR) \
    F(TAUROS) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(DITTO) \
    F(EEVEE) \
    F(VAPOREON) \
    F(JOLTEON) \
    F(FLAREON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ESPEON)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(UMBREON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LEAFEON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(GLACEON)) \
    KANTO_DEX_IF(P_GEN_6_CROSS_EVOS, F(SYLVEON)) \
    F(PORYGON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PORYGON2)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(PORYGON_Z)) \
    F(OMANYTE) \
    F(OMASTAR) \
    F(KABUTO) \
    F(KABUTOPS) \
    F(AERODACTYL) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MUNCHLAX)) \
    F(SNORLAX) \
    F(ARTICUNO) \
    F(ZAPDOS) \
    F(MOLTRES) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEWTWO) \

#define KANTO_DEX_COUNT (KANTO_DEX_MEW + 1)
#define HOENN_DEX_COUNT (HOENN_DEX_RAGING_BOLT + 1)

#define REGIONAL_DEX_COUNT (IS_FRLG ? KANTO_DEX_COUNT : HOENN_DEX_COUNT)

#define DECAGRAMS_IN_POUND             453592
#define CM_PER_INCH                    2.54
#define CM_PER_INCH_FACTOR             (CM_PER_INCH * 100)
#define INCHES_IN_FOOT                 12
#define INCHES_IN_ONE_AND_HALF_FOOT    (INCHES_IN_FOOT * 1.5)
#define INCHES_IN_FOOT_FACTOR          (INCHES_IN_FOOT * 10)

#define WEIGHT_HEIGHT_STR_LEN          16
#define WEIGHT_HEIGHT_STR_MEM          (WEIGHT_HEIGHT_STR_LEN * sizeof(u8))

#define DEX_HEADER_X                   96
#define DEX_Y_TOP                      57
#define DEX_Y_BOTTOM                   73
#define DEX_MEASUREMENT_X              129

#define DEX_HGSS_HEADER_X_PADDING      59
#define DEX_HGSS_Y_TOP_PADDING         7
#define DEX_HGSS_Y_BOTTOM_PADDING      4
#define DEX_HGSS_MEASUREMENT_X_PADDING 51

enum
{
    DEX_MODE_HOENN,
    DEX_MODE_NATIONAL
};

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

#endif // GUARD_CONSTANTS_POKEDEX_H
