gText_Birch_Welcome::
	.string "Ah... A child?\p"
	.string "Two of you... What are you doing\n"
	.string "out here?\p"
	.string "Me? I am... a traveler.\p"
	.string "A wandering soul, looking for new lands.\p"
	.string "My name is Stephen. I come from the\n"
	.string "region of Kanto.\p"
	.string "Oh? The strange capsule?\p"
	.string "This is a Poké Ball. It holds a\n"
	.string "POKéMON inside.\p"
	.string "...! You don't know what that is?!\n"
	.string "Impossible! POKéMON are everywhere!\p"
	.string "... Demons? Legends of them... \n"
	.string "I see...\p"
	.string "Well, allow me to show you, then.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This here is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ahaha, don't worry about Tyranitar's\n"
	.string "appearance. It is no demon, no, it is\l"
	.string "quite far from one.\p"
	.string "People live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "From what I've seen though, this\n"
	.string "region mostly uses them for battle...\p"
	.string "I have seen great bloodshed and \n"
	.string "sorrow brought by the POKéMON\l"
	.string "of this land.\p"
	.string "To discuss such things with children\n"
	.string "like you... Let us stop here.\l"
	.string "Yes, indeed.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "I can't quite make out your\n"
	.string "appearance from here.\p"
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "I see!\p"
	.string "You're {PLAYER}{KUN} from a nearby \n"
	.string "village named Damatra.\l"
	.string "Very well.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "If you don't mind...\n"
	.string "could I stay at Damatra for a\l"
	.string "little while?\p"
	.string "I'm not too keen on ending my\n"
	.string "little adventure here, heh.\p"
	.string "Worry not, I shall protect you\n"
	.string "from the wild POKéMON on the way\l"
	.string "back to the village.\p"
	.string "You must have a chief, yes?\n"
	.string "Bring me to them.\p"
	.string "$"
